version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.8.3
    steps:
      - checkout
      - run:
          name: Zipping Files and Install AWS-Cli
          command: |
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install
            sudo apt-get update -y
            sudo apt-get install -y less
            ls -al
            zip -r webapp.zip webapp.py appspec.yml
            echo "Zip Done"
            sudo chmod 775 webapp.zip
            ls -al
      - run:
          name: Code Deployment
          command: |
            ls -al
            aws lambda update-function-code --function-name MyLambdaFunction --zip-file webapp.zip
          # aws s3 cp webapp.zip s3://codedeploy-kmvanesa-me
          # aws deploy create-deployment --application-name csye6225-lambda --deployment-group-name csye6225-lambda-deployment --description "CSYE6225" --region us-east-1 --s3-location bucket=codedeploy-kmvanesa-me,bundleType=YAML,key=webapp.zip